VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Procedure"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'Version 5/27/24
'This class defines attributes of a coded procedure (code in other workbook) to be tested
Public Enabled As Boolean 'Enable running tests for the procedure
Public name As String 'Name of test



